//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGorev
    {
        public int GorevID { get; set; }
        public string GorevAd { get; set; }
        public Nullable<int> Departman { get; set; }
        public int Durum { get; set; }
    
        public virtual TblDepartman TblDepartman { get; set; }
        public virtual TblDurum TblDurum { get; set; }
    }
}
